### ISSUE TITLE
Is there a way to play with the path tracer settings at runtime through ImGui?

### ISSUE THREAD

**Issue by TomClabault** [sergcpp/DummyEngine#7]
Pretty much title.

I can't seem to find any keybind (if any) to open the ImGui UI and play with the number of bounces / light tree / ...

**Comment by sergcpp** [comment]
Not for now. I only use some native debugging UI which is hidden in release builds.
To run pathtracer, you can use *_pt.bat scripts after executable is built (like run_ai043_06_pt.bat). I will post a release build soon as well.
I am mostly trying to create a renderer that does not require much configuration and provides reasonable defaults.
